In [1]:
print("Tutorial about NumPy")

Tutorial about NumPy


In [3]:
my_list = [1,2,3]
import numpy as np
np.array(my_list)

array([1, 2, 3])

In [4]:
my_mat = [[1,2,3],[4,5,6]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [10]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [12]:
np.ones((2,2))

array([[ 1.,  1.],
       [ 1.,  1.]])

In [15]:
np.linspace(0,5,5)

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ])

In [17]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [18]:
np.random.rand(5)

array([ 0.22057679,  0.20821196,  0.93030839,  0.40795947,  0.37720228])

In [19]:
np.random.rand(5,5)

array([[ 0.0178983 ,  0.74942826,  0.87049494,  0.24186455,  0.62961559],
       [ 0.24554815,  0.88668155,  0.86682259,  0.75177437,  0.0090691 ],
       [ 0.70331508,  0.89658215,  0.65483752,  0.9923898 ,  0.52366353],
       [ 0.44332142,  0.23728181,  0.72526706,  0.49927529,  0.97847152],
       [ 0.9995011 ,  0.17167627,  0.29911521,  0.69717723,  0.95542509]])

In [20]:
np.random.randn(2)

array([-0.72219528, -0.39601105])

In [42]:
arr = np.random.randint(1,100,10)

In [43]:
arr1 = arr.reshape(5,2)

In [44]:
arr1.max()

81

In [45]:
arr1.min()

5

In [46]:
arr1.argmax()

0

In [47]:
arr1.argmin()

6

In [50]:
arr1.shape

(5, 2)

In [51]:
arr1.dtype

dtype('int32')

In [52]:
arr = np.arange(0,11)

In [53]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
arr[3]

3

In [55]:
arr[1:5]

array([1, 2, 3, 4])

In [56]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [57]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [58]:
arr[0:5] = 100

In [61]:
arr = np.arange(0,11)

In [62]:
slice_of_arr = arr[0:6] 

In [63]:
slice_of_arr[:] = 99

array([0, 1, 2, 3, 4, 5])

In [66]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [67]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [68]:
arr_copy = arr.copy()

In [71]:
arr_copy[:] = 100

In [72]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [73]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [74]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [75]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [76]:
arr_2d[0][0]

5

In [77]:
arr_2d[0]

array([ 5, 10, 15])

In [78]:
arr_2d[2,1]

40

In [80]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [81]:
arr_2d[1:,:2]

array([[20, 25],
       [35, 40]])

In [90]:
arr = np.array([4,3,9,2,1,7,8])

In [91]:
bool_arr = arr>5

In [92]:
arr[bool_arr]

array([9, 7, 8])

In [93]:
arr + arr

array([ 8,  6, 18,  4,  2, 14, 16])

In [94]:
arr * arr

array([16,  9, 81,  4,  1, 49, 64])

In [95]:
arr * 4

array([16, 12, 36,  8,  4, 28, 32])

In [96]:
arr1 = np.arange(0,16)

In [100]:
np.sqrt(arr)

array([ 2.        ,  1.73205081,  3.        ,  1.41421356,  1.        ,
        2.64575131,  2.82842712])

In [101]:
np.max(arr)

9